services:
  mysql:
    image: mysql:8.0
    container_name: fruit-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fruitdb
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-hmysql", "-uroot", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: fruit-api
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://mysql:3306/fruitdb
      DB_USER: root
      DB_PASSWORD: root

volumes:
  mysql_data: